### ISSUE TITLE
loadscss when parsing multiple classes with nested pseudo class

### ISSUE THREAD

**Issue by prateekrajgautam** [GeneratorJs/generatorjs.cdn#1]
```scss
classa, classb {
    property:value;

    &:hover {
        p1:p2
    }
}

```
will give output as

```css
classa, classb {
    property:value;
}

classa, classb:hover {
    p1:p2
}
// here pseudo class is applied to only last class

```
